#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=10

PROG=/usr/bin/i2pd
USER=i2pd
GROUP=i2pd
PIDFILE=/var/run/i2pd.pid
DATADIR=/var/lib/i2pd
RUNTIMECONF=/tmp/i2pd.conf
TUNDIR=/etc/i2pd/tunnels.d
CERTSDIR=/usr/share/i2pd/certificates

start_instance() {
	local cfg="$1" data_dir
	config_get data_dir "$cfg" data_dir "$DATADIR"

	[ -n "$data_dir" ] || data_dir="$DATADIR"
	mkdir -p "$data_dir" "$TUNDIR"
	chown "$USER:$GROUP" "$data_dir"
	chown -R "$USER:$GROUP" "$TUNDIR"

	rm -rf "$data_dir/certificates"
	ln -s "$CERTSDIR" "$data_dir/certificates"

	/usr/libexec/i2pd/generate-config || return 1
	touch "$PIDFILE"
	chown "$USER:$GROUP" "$PIDFILE"

	procd_open_instance
	procd_set_param command "$PROG" --datadir="$data_dir" --conf="$RUNTIMECONF" --pidfile "$PIDFILE"
	procd_set_param env HOME="$data_dir"
	procd_set_param limits nofile=4096
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param user "$USER"
	procd_set_param group "$GROUP"
	procd_set_param pidfile "$PIDFILE"
	procd_set_param respawn
	procd_close_instance
}

start_service() {
	config_load i2pd
	config_foreach start_instance i2pd
}

stop_service() {
	procd_kill i2pd
	sleep 5
	rm -f "$PIDFILE"
}

reload_service() {
	/usr/libexec/i2pd/generate-config || return 1
	procd_send_signal i2pd
}
